<?php

namespace Tests\Feature;

use App\Models\Block;
use App\Models\Booking;
use App\Models\Room;
use App\Repositories\BlockRepository\BlockRepository;
use App\Repositories\BookingRepository\BookingRepository;
use App\Repositories\RoomRepository\RoomRepository;
use Carbon\Carbon;
use Database\Seeders\ExampleSeeder;
use Database\Seeders\RoomSeeder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\Sequence;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BlockRepositoryTest extends TestCase
{
    use RefreshDatabase;
    protected Collection $rooms;
    protected Collection $bookings;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // seed rooms
        $this->rooms = Room::factory()
            ->count(3)
            ->state(new Sequence(
                [
                    'name' => 'Room A',
                    'capacity' => 6
                ],
                [
                    'name' => 'Room B',
                    'capacity' => 4
                ],
                [
                    'name' => 'Room C',
                    'capacity' => 2
                ],
            ))
            ->create();

        // seed blocks
        Block::factory()
            ->create([
                'room_id'   => $this->rooms[1]->id,
                'starts_at' => Carbon::createFromDate(2023, 1, 1),
                'ends_at'   => Carbon::createFromDate(2023, 1, 10)
            ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_get_blocks_group_by_startsAt_endsAt_a_day()
    {

        $startsAt   = Carbon::create(2023,01,2);
        $endsAt     = Carbon::create(2023,01,2);
        $bookings   = (new BlockRepository())->getBlocksGroupByStartsAtEndsAt($startsAt, $endsAt);

        $expected = [
            [
                "aggregate" => 1,
                "starts_at" => "2023-01-01",
                "ends_at" => "2023-01-10"
            ]
        ];

        $this->assertEquals(json_encode($expected), json_encode($bookings->toArray()));
    }

    public function test_get_blocks_group_by_startsAt_endsAt_for_a_mount()
    {
        $startsAt   = Carbon::create(2023,01,1);
        $endsAt     = Carbon::create(2023,01,31);
        $bookings = (new BlockRepository())->getBlocksGroupByStartsAtEndsAt($startsAt, $endsAt);

        $expected = [
            [
                "aggregate" => 1,
                "starts_at" => "2023-01-01",
                "ends_at" => "2023-01-10"
            ]
        ];

        $this->assertEquals(json_encode($expected), json_encode($bookings->toArray()));
    }

    public function test_get_blocks_group_by_startsAt_endsAt_for_a_day_and_rooms()
    {
        $startsAt   = Carbon::create(2023,01,6);
        $endsAt     = Carbon::create(2023,01,6);
        $bookings   = (new BlockRepository())->getBlocksGroupByStartsAtEndsAt($startsAt, $endsAt, [$this->rooms[1]->id, $this->rooms[2]->id]);

        $expected = [
            [
                "aggregate" => 1,
                "starts_at" => "2023-01-01",
                "ends_at" => "2023-01-10"
            ]
        ];

        $this->assertEquals(json_encode($expected), json_encode($bookings->toArray()));
    }

    public function test_get_blocks_group_by_startsAt_endsAt_for_a_day_and_rooms_return_empty()
    {
        $startsAt   = Carbon::create(2023,01,6);
        $endsAt     = Carbon::create(2023,01,6);
        $bookings   = (new BlockRepository())->getBlocksGroupByStartsAtEndsAt($startsAt, $endsAt, [$this->rooms[0]->id]);

        $this->assertEquals(json_encode([]), json_encode($bookings->toArray()));
    }
}
